IfElse Task with Unit Tests.
KluevJakov/MyInternship pull request #2
Opened 2021-09-24 13:56 UTC by KluevJakov

2021-09-24 14:25 UTC, kovinz requested changes

2021-09-24 14:25 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/IfElseTask.java
> +        if (n%2 != 0) {
please add spaces around '%'

2021-09-24 14:25 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/IfElseTask.java
> +                return "Not Weird";
Please move "Not Weird" and "Weird" to constants (private static final String)

2021-09-24 14:25 UTC, kovinz commented on src/test/java/com/github/KluevJakov/myinternship/IfElseTest.java
> +        assertEquals("Weird", IfElseTask.solveTask(3));
Please move "Not Weird" and "Weird" to constants (private static final String) (copy-paste their declaration from  IfElseTask class)

2021-09-24 14:25 UTC, kovinz commented on src/test/java/com/github/KluevJakov/myinternship/IfElseTest.java
> +    }
UTs need to include the end cases in if statements - add tests for numbers: 2 5 6 20

2021-09-27 01:54 UTC, KluevJakov commented on src/main/java/com/github/KluevJakov/myinternship/tasks/IfElseTask.java
> +        if (n%2 != 0) {
Done

2021-09-27 09:05 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/IfElseTask.java
> +    private static final String neg = "Not Weird";
constants (static final) have contact for naming - name the first one as WEIRD, the second as NOT_WEIRD

2021-09-27 09:05 UTC, kovinz commented on src/test/java/com/github/KluevJakov/myinternship/IfElseTest.java
> +    private static final String neg = "Not Weird";
the same naming convention applies here

2021-09-27 09:52 UTC, kovinz approved these changes

2021-09-27 11:34 UTC, merged