#3 StreamTask
KluevJakov/MyInternship pull request #4
Opened 2021-09-27 02:10 UTC by KluevJakov

2021-09-28 09:38 UTC, kovinz requested changes

2021-09-28 09:38 UTC, kovinz commented on src/test/java/com/github/KluevJakov/myinternship/StreamTest.java
> +        check.put(1,new ArrayList<>(Arrays.asList("o5")));
add space after comma please

2021-09-28 09:38 UTC, kovinz commented on src/test/java/com/github/KluevJakov/myinternship/StreamTest.java
> +        check.put(1,new ArrayList<>(Arrays.asList("o5")));
the same applies to other tests also

2021-09-28 09:38 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/StreamTask.java
> +                .boxed()
remove this step - you box int to Integer on this step and on the next "filter" step when you compare it to 0 you will unbox every item then compare it and then box it again - seems like too much work for nothing

2021-09-28 09:38 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/StreamTask.java
> +                .filter(e -> e > 0)
vars in lambda should also have some meaningful name - please rename

2021-09-28 09:38 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/StreamTask.java
> +                .sorted()
why do you need sorting in this task?

2021-09-28 09:38 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/StreamTask.java
> +                .filter(e -> e > 0)
also task says "filter out negative values". Zero isn't negative

2021-09-28 09:38 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/StreamTask.java
> +                .map(e -> e % 2 == 0 ? "e" + e : "o" + e)
please rename var in lambda

2021-09-28 09:38 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/StreamTask.java
> +                .collect(Collectors.toMap(
Collectors have better method for grouping by some attribute - please check java doc for Collectors class and find it :)

2021-09-28 09:38 UTC, kovinz commented on src/main/java/com/github/KluevJakov/myinternship/tasks/StreamTask.java
> +        Map<Integer, List<String>> result = Arrays.stream(input)
why not to remove variable "result" and just return result of stream?
P.S. IDEA proposes the same and shows warning

2021-09-28 09:38 UTC, kovinz commented on src/test/java/com/github/KluevJakov/myinternship/StreamTest.java
> +public class StreamTest {
please add tests for negative cases - such as "all values are negative", "empty array is passed to the method"

2021-09-28 09:38 UTC, kovinz commented on src/test/java/com/github/KluevJakov/myinternship/StreamTest.java
> +public class StreamTest {
plus after fixing bug with 0 - add test where 0 will be present among other items
this is a good practice to add UT to check for a fixed bug

2021-09-29 06:51 UTC, KluevJakov commented on src/main/java/com/github/KluevJakov/myinternship/tasks/StreamTask.java
> +                .sorted()
From the example, it seemed to me that the numbers should also be sorted in ascending order, but after rereading, I realized that the assignment did not say about this

2021-09-30 14:43 UTC, kovinz approved these changes

2021-09-30 14:54 UTC, merged